#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ ! -f ~/bin/bash/colors ]]; then
	source "$DIR"/colors
else
	source ~/bin/bash/colors
fi

print_error() {
	echo -ne "${RED_FG}${BOLD}error: ${RESET}"
	echo -n "$@"
	echo ""
}
print_info() {
	echo -ne "${GREEN_FG}${BOLD}info: ${RESET}"
	echo -n "$@"
	echo ""
}
print_debug() {
	if [[ "$VERBOSE" == "verbose" ]]; then
		echo -ne "${MAGENTA_FG}${BOLD}debug: ${RESET}"
		echo -n "$@"
		echo ""
	fi
}
print_warning() {
	echo -ne "${YELLOW_FG}${BOLD}warn: ${RESET}"
	echo -n "$@"
	echo ""
}

parse_git_branch() {
	if git rev-parse --git-dir >/dev/null 2>&1; then
		br=$(git branch 2>/dev/null | sed -n '/^\*/s/^\* //p')
	else
		return 0
	fi
	echo -e "[$br] "
}

